import type { PatentMatter, PdfExtractionResult } from "./types";

export const blankSb16Sample: PdfExtractionResult = {
  fileName: "sb0016_2.pdf",
  hasAcroFormFields: true,
  fallbackNeeded: false,
  warnings: ["Blank form sample: required fields are available but not filled."],
  rawFields: {
    "Express Mail Label No": "",
    "TITLE OF THE INVENTION 500 characters maxRow1": "",
    "Firm or Individual Name": "",
    Address: "",
    City: "",
    State: "",
    Zip: "",
    Country: "",
    Telephone: "",
    Email: "",
    "Number of Sheets": "",
    "Number of Pages": "",
    "TYPED OR PRINTED NAME": "",
    DATE: "",
    "DOCKET NUMBER": "",
  },
  normalized: {
    inventionTitle: "",
    inventors: [],
    correspondenceAddress: {
      firmOrIndividualName: "",
      address: "",
      city: "",
      state: "",
      zip: "",
      country: "",
      telephone: "",
      email: "",
    },
    entityStatus: "undisclosed",
    applicationParts: {
      applicationDataSheet: false,
      drawings: false,
      drawingSheetCount: "",
      specificationPageCount: "",
      cds: false,
      cdCount: "",
      other: "",
    },
    governmentInterest: {
      madeByGovernment: false,
      madeUnderContract: false,
      agencyName: "",
      contractNumber: "",
    },
    signerName: "",
    signatureDate: "",
    docketNumber: "",
    feePaymentMethod: "",
  },
};

export const makeInitialMatter = (): PatentMatter => ({
  inventionId: `INV-${new Date().getFullYear()}-0001`,
  matterId: "MAT-SB16-0001",
  inventionDisclosureId: "",
  attorneyDocketNumber: "",
  title: "Untitled provisional intake",
  assignee: { id: "assignee-1", name: "" },
  inventors: [],
  currentLifecycleStatus: "intake",
  expectedExpirationDate: "",
  maintenanceFeeStatus: "not applicable until grant",
  notes: "",
  identifiers: [
    { id: "internal-invention", label: "Internal invention ID", value: "INV-2026-0001", authority: "internal", source: "client", isOfficialLegalIdentifier: false },
    { id: "matter", label: "Matter ID", value: "MAT-SB16-0001", authority: "internal", source: "client", isOfficialLegalIdentifier: false },
    { id: "disclosure", label: "Invention disclosure ID", value: "", authority: "internal", source: "client", isOfficialLegalIdentifier: false },
    { id: "attorney-docket", label: "Attorney docket number", value: "", authority: "internal", source: "assignee/counsel", isOfficialLegalIdentifier: false },
    { id: "provisional", label: "Provisional application number", value: "", authority: "uspto", source: "USPTO", isOfficialLegalIdentifier: true },
    { id: "nonprovisional", label: "Nonprovisional application number", value: "", authority: "uspto", source: "USPTO", isOfficialLegalIdentifier: true },
    { id: "publication", label: "Publication number", value: "", authority: "uspto", source: "USPTO", isOfficialLegalIdentifier: true },
    { id: "patent", label: "Patent number", value: "", authority: "uspto", source: "USPTO", isOfficialLegalIdentifier: true },
    { id: "pct", label: "PCT number", value: "", authority: "pct", source: "WIPO", isOfficialLegalIdentifier: true },
    { id: "priority", label: "Priority claims", value: "", authority: "provider-reference", source: "manual", isOfficialLegalIdentifier: false },
    { id: "docdb", label: "EPO DOCDB family ID", value: "", authority: "family-provider", source: "EPO", isOfficialLegalIdentifier: false },
    { id: "inpadoc", label: "INPADOC family ID", value: "", authority: "family-provider", source: "EPO", isOfficialLegalIdentifier: false },
    { id: "google", label: "Google Patents family / related-publication reference", value: "", authority: "family-provider", source: "Google Patents", isOfficialLegalIdentifier: false },
  ],
  lifecycleEvents: [
    { id: "event-1", type: "provisional_cover_sheet_parsed", label: "Provisional cover sheet parsed", date: new Date().toISOString().slice(0, 10), status: "complete", sourceRecordIds: ["source-sample"] },
    { id: "event-2", type: "provisional_filed", label: "Provisional filed", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-3", type: "nonprovisional_or_pct_filed", label: "Nonprovisional or PCT filed", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-4", type: "application_published", label: "Application published", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-5", type: "office_action_received", label: "Office action received", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-6", type: "response_filed", label: "Response filed", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-7", type: "notice_of_allowance", label: "Notice of allowance", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-8", type: "issue_fee_paid", label: "Issue fee paid", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-9", type: "patent_granted", label: "Patent granted", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-10", type: "maintenance_fee_window_opened", label: "Maintenance fee window opened", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-11", type: "maintenance_fee_paid_or_missed", label: "Maintenance fee paid or missed", date: "", status: "pending", sourceRecordIds: [] },
    { id: "event-12", type: "patent_expired_abandoned_or_terminally_disclaimed", label: "Patent expired, abandoned, or terminally disclaimed", date: "", status: "pending", sourceRecordIds: [] },
  ],
  sourceRecords: [
    { id: "source-sample", label: "Blank SB/16 sample fields", sourceType: "pdf", capturedAt: new Date().toISOString(), rawFieldNames: Object.keys(blankSb16Sample.rawFields) },
  ],
  deadlines: [
    { id: "deadline-1", label: "12-month provisional conversion watch", dueDate: "", status: "watch", basis: "Calculated after provisional filing date is entered." },
    { id: "deadline-2", label: "Maintenance fee windows", dueDate: "", status: "watch", basis: "Stub until patent grant and USPTO maintenance fee data are attached." },
  ],
});
